server {
  listen 6663;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api.php {
    proxy_pass https://www.glivestreaming.com;
    proxy_set_header Host www.glivestreaming.com;
    proxy_set_header User-Agent "yaak";
    proxy_set_header Accept "*/*";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
