server {
  listen 6663;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api.php {
    proxy_pass https://www.glivestreaming.com;
    resolver 8.8.8.8 1.1.1.1 valid=300s;
    proxy_ssl_server_name on;
    proxy_ssl_name www.glivestreaming.com;
    proxy_ssl_protocols TLSv1.2 TLSv1.3;
    proxy_set_header Host www.glivestreaming.com;
    proxy_set_header User-Agent "yaak";
    proxy_set_header Accept "*/*";
  }

  location = /h5link {
    proxy_pass https://www.glivestreaming.com/api.php?action=geth5link&$args;
    resolver 8.8.8.8 1.1.1.1 valid=300s;
    proxy_ssl_server_name on;
    proxy_ssl_name www.glivestreaming.com;
    proxy_ssl_protocols TLSv1.2 TLSv1.3;
    proxy_set_header Host www.glivestreaming.com;
    proxy_set_header User-Agent "yaak";
    proxy_set_header Accept "*/*";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
